/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
wandb: Currently logged in as: rohanvk (rohanvk-carnegie-mellon-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.6
wandb: Run data is saved locally in /home/rvk/wandb/run-20250909_204513-d6gyq3pp
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run twilight-cherry-149
wandb: ‚≠êÔ∏è View project at https://wandb.ai/rohanvk-carnegie-mellon-university/ffno2d
wandb: üöÄ View run at https://wandb.ai/rohanvk-carnegie-mellon-university/ffno2d/runs/d6gyq3pp
  0%|          | 0/35 [00:00<?, ?it/s]  0%|          | 0/35 [00:01<?, ?it/s]
Error executing job with overrides: ['model=ffno_2d/ffno_2d', 'dataset=ns/ns_naive_true_mres']
Traceback (most recent call last):
  File "/home/rvk/main_2d.py", line 196, in main
    loss_history, val_loss_history = train(
                                     ~~~~~^
                        model, train_loader, val_loader,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        optimizer, scheduler, y_normalizer=y_normalizer, use_normalizer=use_normalizer,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        time=1, model_type=model_type, epochs=epochs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rvk/train/training.py", line 36, in train
    pred_y = model(batch_x)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/parallel/data_parallel.py", line 193, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/parallel/data_parallel.py", line 212, in parallel_apply
    return parallel_apply(
        replicas, inputs, kwargs, self.device_ids[: len(replicas)]
    )
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/parallel/parallel_apply.py", line 126, in parallel_apply
    output.reraise()
    ~~~~~~~~~~~~~~^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
torch.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/parallel/parallel_apply.py", line 96, in _worker
    output = module(*input, **kwargs)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rvk/models/ffno.py", line 229, in forward
    x_new, _ = layer(x)
               ~~~~~^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rvk/models/spectral_convolution.py", line 252, in forward
    b = self.backcast_ff(x)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rvk/models/custom_layer.py", line 67, in forward
    x = layer(x)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/modules/dropout.py", line 70, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user_data/rvk/pde/lib/python3.13/site-packages/torch/nn/functional.py", line 1425, in dropout
    _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
                                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB. GPU 0 has a total capacity of 10.90 GiB of which 1.06 GiB is free. Including non-PyTorch memory, this process has 9.84 GiB memory in use. Of the allocated memory 9.60 GiB is allocated by PyTorch, and 12.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
srun: error: shire-1-6: task 0: Exited with exit code 1
